### ISSUE TITLE
La pompa empuja a Yuno si lleva velocidad

### ISSUE THREAD

**Issue by elisatodd** [josemiguelvdz/Bubble-Cat#1]
% Errores encontrados
% Elisa Todd Rodríguez
% 19/05/2021

### Descripción
Cuando controlamos a una pompa y chocamos contra un elemento físico del escenario, se destruye, por lo tanto se destruye al chocar con Yuno. Pero en caso de que la pompa lleve una velocidad alta (ver vídeo), esta no sólo se destruye al chocar, sino que también empuja a Yuno, desplazándole una distancia dependiente de dicha velocidad.

### Pasos
1. Controlar una pompa.
2. Alejarse de Yuno.
3. Moverse hacia Yuno, sin parar el movimiento de la pompa.
4. Impactar contra Yuno.

### Captura de pantalla o vídeo
![ErrorPompa1](https://user-images.githubusercontent.com/81906237/118774078-bdd5d200-b885-11eb-9e16-5b9c94b85f90.png)
![ErrorPompa2](https://user-images.githubusercontent.com/81906237/118774081-be6e6880-b885-11eb-9acc-762c5cf7162e.png)
![ErrorPompa3](https://user-images.githubusercontent.com/81906237/118774083-be6e6880-b885-11eb-8ed9-b8d761c047cf.png)

**Comment by josemiguelvdz** [comment]
Esto no pasa, lo que ha ocurrido es que al explotar la pompa recuperas inmediatamente el control del personaje, moviéndote tú con el personaje. Ahora que el personaje está animado se ve mucho mejor cuándo te mueves tú. Si pruebas a explotar la pompa como dices tú pero dejando de pulsar justo antes de chocarte con el personaje, verás que el choque es mínimo y no afecta a la experiencia de juego.
