### ISSUE TITLE
Explosión de bomba de butano invisible e inevitable

### ISSUE THREAD

**Issue by Yavi123** [josemiguelvdz/Bubble-Cat#10]
% Javier Villegas
% 25/05/2021

### Descripción

Cuando Bastet lanza la bomba de butano y ésta explota la animación de la explosión no se ve. Además si Yuno no llega a meterla en una pompa, al explotar (tanto si lo causamos nosotros por disparar a la bomba, como si dejamos que caiga) dañará a Yuno aun si está muy lejos.

### Pasos 

1. Esperar a que Bastet lance la bomba y hacer que explote.

**Comment by josemiguelvdz** [comment]
Ya se ha añadido una animación para la explosión y ajustado su radio de explosión para que sea más justo.
