### ISSUE TITLE
Salirse del mapa

### ISSUE THREAD

**Issue by Yavi123** [josemiguelvdz/Bubble-Cat#11]
% Javier Villegas
% 25/5/2021

### Descripción

Si mientras Yuno cae y se pega a una pared, al aterrizar es posible salirse fuera de la zona de juego. 
No funciona siempre, pero parece más probable que ocurra cuanto más rápido se caiga.

### Pasos 

1. Encontrar una zona del juego que te permita caer cierta distancia mientras estás pegado a una pared (la caída tras destruir la pared con la bolsa de basura en la escena de mecánicas básicas es un buen sitio).
2. Saltar lo máximo posible.
3. Mientras mantener pulsado la tecla correspondiente para pegarse a la pared

### Captura de pantalla o vídeo

https://youtu.be/uteuNm2w0VE

**Comment by josemiguelvdz** [comment]
Pasaba porque las colisiones se comprobaban de forma discreta. Ahora se comprueban de forma continua y debería funcionar bien.
