### ISSUE TITLE
Fallo con las colisiones

### ISSUE THREAD

**Issue by AntonioPove** [josemiguelvdz/Bubble-Cat#12]
% Antonio Povedano Ortiz
% 25-5-21

### Descripción

En la parte del nivel donde cae bolsas de basura, he realizado un salto para llegar a las parte de las tuberías, pero Yuno no se ha apoyado en el suelo y se ha quedado atrapada dentro de la pared.

### Pasos 

1. Saltar desde la plataforma rompible al lugar donde se encuentran las tuberías.
2. Yuno quedará atrapada dentro de la pared al chocar con esta.

### Captura de pantalla o vídeo

![err](https://user-images.githubusercontent.com/79278677/119552038-9194e680-bd9a-11eb-9157-85015dcee0a5.png)
![errr](https://user-images.githubusercontent.com/79278677/119552040-922d7d00-bd9a-11eb-9944-1e2f2693c92c.png)

**Comment by josemiguelvdz** [comment]
Pasaba porque las colisiones se comprobaban de forma discreta. Ahora se comprueban de forma continua y debería funcionar bien.
