### ISSUE TITLE
Imposibilidad de instanciar una pompa mientras se salta

### ISSUE THREAD

**Issue by elisatodd** [josemiguelvdz/Bubble-Cat#13]
% Imposibilidad de instanciar una pompa mientras se salta
% Elisa Todd Rodríguez 
% 27/05/2021

### Descripción

Durante la prueba de las mecánicas básicas, se encuentra la imposibilidad de crear una pompa (pulsando la tecla ‘Q’) si el momento cuando se pulsa esta tecla el personaje (Yuno) está saltando.

### Pasos 

1.	Controlar a Yuno.
2.	Pulsar la tecla Espacio para saltar.
3.	Seguidamente, antes de que Yuno vuelva a tocar el suelo, pulsar la ‘Q’.
4.	Observar cómo no se ha instanciado una pompa.

**Comment by javics2002** [comment]
Esa era nuestra intención. Perdona, se nos ha pasado especificarlo en el plan de pruebas
