### ISSUE TITLE
Los murciélagos no vuelven a su posición inicial

### ISSUE THREAD

**Issue by elisatodd** [josemiguelvdz/Bubble-Cat#14]
% Los murciélagos no vuelven a su posición inicial
% Elisa Todd Rodríguez
% 27/05/2021

### Descripción

Cuando Yuno entra en el campo de visión de un murciélago, este empieza a perseguirle, hasta que Yuno sale de su campo de visión. Según indica el plan de pruebas, deberían volver a su posición **inicial** una vez esto ocurra. Sin embargo, los murciélagos se quedan en el último punto en el que veían a Yuno, de manera que no vuelven a su posición inicial.

### Pasos 

1.	Controlar a Yuno.
2.	Acercarse a uno o varios murciélagos, para que te vean.
3.	Huir de los murciélagos hasta que te dejen de perseguir.
4.	Volver hacia atrás pasado un tiempo.
5.	Observar cómo los murciélagos no están en su posición inicial.

### Captura de pantalla o vídeo

Se observa cómo los murciélagos pierden de vista a Yuno en el punto de la imagen 2, y al regresar se encuentran justo sobre ese punto.

1: 
![murcielagos0](https://user-images.githubusercontent.com/81906237/119783768-d66d6a00-becd-11eb-9942-d4bd97f13103.png)

2:
![murcielagos1](https://user-images.githubusercontent.com/81906237/119783770-d66d6a00-becd-11eb-97f8-dc8a3f49133c.png)

3:
![murcielagos2](https://user-images.githubusercontent.com/81906237/119783766-d5d4d380-becd-11eb-9732-c1368c4c1ece.png)

4:
![murcielagos3](https://user-images.githubusercontent.com/81906237/119783767-d66d6a00-becd-11eb-86a9-cbf8ac1a6a63.png)

**Comment by josemiguelvdz** [comment]
Es un fallo nuestro, los murciélagos no deberían volver a su posición inicial, sino que deberían subir al techo y quedarse colgados otra vez hasta que vuelvan a ver a Yuno (si es que lo hacen alguna vez).
