### ISSUE TITLE
Se cancela el salto

### ISSUE THREAD

**Issue by alvarolozrod** [josemiguelvdz/Bubble-Cat#15]
% Álvaro Lozano Rodríguez
% 28/05/2021

Descripción
En el momento en que salto y le doy a la E, el salto se cancela al instante y da igual a la altura que se encuentre el personaje que baja al momento.

Pasos:
- Mantener el espacio para dar un salto grande
- Pulsar la E
- Veremos que el salto se cancela en el aire.

Imagen:
![2021-05-28 (8)](https://user-images.githubusercontent.com/79278632/120016730-3b67b380-bfe5-11eb-91b4-b4bd141feb85.png)

**Comment by Roodri02** [comment]
No se como habrás conseguido eso pero he probado durante un tiempo y han probado el resto de desarrolladores y no nos pasa.
Igual es que no solo hay que pulsar la E pero en ese caso nos falta información
