### ISSUE TITLE
Se traspasa la puerta con la pompa

### ISSUE THREAD

**Issue by alvarolozrod** [josemiguelvdz/Bubble-Cat#16]
% Álvaro Lozano Rodríguez
% 28/05/2021

Descripción:
Al llegar a la puerta azul donde hay unas rejas encima lasa cuales se supone que son para que pase la pompa, si te pegas a la puerta, la pompa aparece directamente al otro lado.

Pasos: 
- Pegarte a la puerta azul
- Pulsar la Q para crear una pompa
- Se creará una pompa directamente al otro lado de la puerta

Imagen:
![2021-05-28 (9)](https://user-images.githubusercontent.com/79278632/120017199-dfe9f580-bfe5-11eb-8cd2-50884467e9f8.png)

**Comment by javics2002** [comment]
Arreglado, gracias
