### ISSUE TITLE
No se guarda correctamente el nivel

### ISSUE THREAD

**Issue by alvarolozrod** [josemiguelvdz/Bubble-Cat#17]
% Álvaro Lozano Rodríguez
% 28/05/2021

Descripción: 
Al pasar por la zona de la puerta, utilicé para abrirla una caja que estaba al lado de derecho de la puerta, dejando al lado izquierdo otra caja. Crucé la puerta y morí, y al aparecer la caja de la izquierda había desaparecido y había dos cajas en el lado derecho de las puertas. No es molesto para jugar, pero si se hace extraño ver que las cosas han cambiado de sitio.

Pasos:
- Dejar una caja a cada lado de la puerta azul
- Morir
- Las cajas cambian las que eran sus posiciones anteriores

Imágenes: 
- Antes de morir: 
![2021-05-28 (11)](https://user-images.githubusercontent.com/79278632/120017926-bed5d480-bfe6-11eb-9e04-b93380de7dd2.png)

- Después de morir:
![2021-05-28 (10)](https://user-images.githubusercontent.com/79278632/120017947-c9906980-bfe6-11eb-872f-5be7881fcc10.png)

**Comment by Roodri02** [comment]
Realmente, nosotros lo que queremos es que cuando el personaje muera, vuelva al checkpoint, pero aquí el estado del juego no queremos que sea el mismo que antes de morir, sino que se reinicien todos los enemigos, cajas, ..., de tal manera que vuelvas a empezar desde el checkpoint con todo lo necesario.
