### ISSUE TITLE
El camaleón se queda volando

### ISSUE THREAD

**Issue by alvarolozrod** [josemiguelvdz/Bubble-Cat#18]
% Álvaro Lozano Rodríguez
% 28/05/2021

Descripción:
AL coger con la pompa uno de los escupitajos del camaleón y pegarle a él con ello, el camaleón se queda deslizándose sin atacar muy despacio, cómo levitando. SI esperas suficiente tiempo terminara flotando por el aire.

Pasos: 
- Coger un escupitajo de camaleón con la pompa
- Golpear al camaleón con su escupitajo
- El camaleón flotara por la sala

Imagen:
![2021-05-28 (12)](https://user-images.githubusercontent.com/79278632/120018533-98646900-bfe7-11eb-9d1e-04d8e86d2dd6.png)

**Comment by Roodri02** [comment]
Arreglado!
