### ISSUE TITLE
La araña se queda volando

### ISSUE THREAD

**Issue by alvarolozrod** [josemiguelvdz/Bubble-Cat#19]
% Álvaro Lozano Rodríguez
%28/05/2021

Descripción:
Sobre la mitad del nivel, si coges una araña con una pompa y la sueltas en el aire para tirarla al agua, la araña se queda flotando en el aire quieta.

Pasos:
- Coge una araña que esté en el techo con una pompa.
- Suéltala sobre el agua
- La araña se quedará flotando en el aire

Imagen: 
![2021-05-28 (13)](https://user-images.githubusercontent.com/79278632/120019057-43752280-bfe8-11eb-8eeb-0261877b70c3.png)

**Comment by Roodri02** [comment]
Arreglado!
