### ISSUE TITLE
La pompa no se destruye al chocar contra una puerta

### ISSUE THREAD

**Issue by elisatodd** [josemiguelvdz/Bubble-Cat#2]
% Errores encontrados
% Elisa Todd Rodríguez 
% 19/05/2021

### Descripción
Al controlar una pompa, si choca contra una puerta azul (como la localizada en el apartado mecánicas básicas), no explota. Al ser la puerta un objeto físico, debería romper la pompa al chocar.

### Pasos 
1.	Controlar una pompa.
2.	Moverse hasta situarse al lado de una puerta azul, de manera que quede tocando la puerta.

### Captura de pantalla o vídeo
![pompanoserompe](https://user-images.githubusercontent.com/81906237/118810566-4ff0d100-b8ac-11eb-8107-8377e5ff1fe4.png)

**Comment by javics2002** [comment]
Solucionado, gracias
