### ISSUE TITLE
Los Slimes quedan atrapados en un punto tras dejar de ver a Yuno

### ISSUE THREAD

**Issue by elisatodd** [josemiguelvdz/Bubble-Cat#3]
% Errores encontrados
% Elisa Todd Rodríguez 
% 19/05/2021

### Descripción

Es un error que sólo ocurre en un caso concreto: cuando un slime se encuentra sobre una plataforma elevada, ve a Yuno, se coloca sobre el borde de esa plataforma (sin llegar a caer), y Yuno salta sobre él hacia el otro lado. También ocurre si en lugar de saltar sobre él, pasa bajo él (caso de que esté en una plataforma en el aire). Cuando se realiza esta secuencia de movimientos, el slime queda en un mismo punto mirando de un lado a otro pero sin poder moverse. Se queda en este estado hasta que interactúe con algún elemento físico que lo saque de ese punto: Se lo lleve con la pompa, Yuno choque contra él… Además, si Yuno vuelve a ser visto por este slime atascado, no le seguirá, únicamente mirará en su dirección constantemente, hasta que de nuevo lo pierda de vista.

### Pasos 

1.	Controlar a Yuno.
2.	Acercarse a un slime que esté sobre una plataforma (a más altura que el jugador).
3.	Esperar a que el slime se acerque lo máximo posible.
4.	Saltar por encima del slime, sin tocarlo.
5.	Salir del campo de detección del slime.
6.	Observar el atasco.

### Captura de pantalla o vídeo

Vídeo donde se ve el error - > https://youtu.be/yDiikinsgCA

**Comment by D-ROL-S** [comment]
Problema solucionado, en el caso de que es slime detecte al jugador y se quede en el borde.
