### ISSUE TITLE
Disparo de bala involuntaria al salir del modo pausa

### ISSUE THREAD

**Issue by AntonioPove** [josemiguelvdz/Bubble-Cat#4]
% Antonio Povedano Ortiz
% 21-5-21

### Descripción

Si pausamos el juego y le damos a RESUME, Yuno siempre lanzará una bala de manera automática al salir de este modo.

### Pasos 

Detallar los pasos seguidos para poder reproducir el error. Si no se ha podido reproducir, entonces indicarlo igualmente.

1. Acceder al modo pausa dentro de la partida.
2. Al pulsar el botón RESUME veremos que al ir al modo de juego de nuevo este siempre disparará una bala.

**Comment by javics2002** [comment]
Solucionado, gracias
