### ISSUE TITLE
Pérdida de las pastillas de jabón

### ISSUE THREAD

**Issue by AntonioPove** [josemiguelvdz/Bubble-Cat#5]
% Antonio Povedano Ortiz
% Fecha

### Descripción

Cuando Yuno recoge una pastilla de jabón todas las pastillas de jabón obtenidas anteriormente desaparecen.

### Pasos 

1. Tener pastillas de jabón recogidas con anterioridad.
2. Recoger una pastilla de jabón hará que todas las pastillas anteriores desaparezcan.

### Captura de pantalla o vídeo

![1](https://user-images.githubusercontent.com/79278677/119168213-f7166980-ba60-11eb-9e22-0c4756056597.png)
![2](https://user-images.githubusercontent.com/79278677/119168228-fb428700-ba60-11eb-87a0-cb8c253a05b0.png)

**Comment by javics2002** [comment]
Eso es porque no cabe el numero 100. Quise poner pastillas infinitas para las salas de debug, pero simplemente pensé que poner muchas bastaría. Sin embargo, esto nunca llegará a pasar en el juego.
