### ISSUE TITLE
Pinchos no llegan a matar

### ISSUE THREAD

**Issue by Yavi123** [josemiguelvdz/Bubble-Cat#6]
% Javier Villegas
% 25/5/2021

### Descripción

Si durante el periodo de inmunidad Yuno se queda encima de los pinchos, cuando éste acabe Yuno no recibirá daño por los pinchos a no ser que los vuelva a pisar.

### Pasos 

1. Mientras se tiene el casco de burbuja, recibir daño de cualquier forma (incluso de los propios pinchos).
2. Antes de que acabe el periodo de inmunidad, colocarse encima de los pinchos.

### Captura de pantalla o vídeo

![Bubble Cat Screenshot 2021 05 22 - 13 42 06 90](https://user-images.githubusercontent.com/82315353/119506002-c9d20000-bd6d-11eb-8c34-1de74127b525.png)

**Comment by josemiguelvdz** [comment]
Con el diseño de niveles actual, es imposible que ocurra esto.
