### ISSUE TITLE
Araña no llega a matar

### ISSUE THREAD

**Issue by Yavi123** [josemiguelvdz/Bubble-Cat#7]
% Javier Villegas
% 25/05/2021

### Descripción

Cuando la araña le cae en la cabeza a Yuno mientras éste lleva la pompa en la cabeza, y no se mueve, la araña se quedará ahí sin moverse y sin dañar a Yuno aun cuando acaba el tiempo de inmunidad.

### Pasos 

1. Colocarse justo debajo de la araña mientras se tiene el casco de pompa.
2. Dejar que caiga justo encima de Yuno.

### Captura de pantalla o vídeo

![Bubble Cat Screenshot 2021 05 23 - 15 21 56 58](https://user-images.githubusercontent.com/82315353/119506394-2a613d00-bd6e-11eb-975e-87de025f5084.png)

**Comment by javics2002** [comment]
No hemos conseguido arreglarlo. Ni con los métodos Stay. Sin embargo, en cuanto te quieras mover morirás instantáneamente, por lo que tampoco te puedes aprovechar de él. Gracias por el apunte.
