### ISSUE TITLE
Lagartos no reciben daño 

### ISSUE THREAD

**Issue by Yavi123** [josemiguelvdz/Bubble-Cat#8]
% Javier Villegas
% 25/05/2021

### Descripción

Los lagartos aparentemente no se ven afectados por las bombas de butano, ni por las balas, y el ataque a melé los hace retroceder excesivamente.

### Pasos 

1. Intentar infligir daño con las balas, bombas de butano o con el ataque a melé

### Captura de pantalla o vídeo

![Captura](https://user-images.githubusercontent.com/82315353/119506928-a9ef0c00-bd6e-11eb-9f78-74891661ba82.PNG)
![Captura2](https://user-images.githubusercontent.com/82315353/119506934-ac516600-bd6e-11eb-9ff2-e266c0d3d16a.PNG)
![Captura3](https://user-images.githubusercontent.com/82315353/119506941-ae1b2980-bd6e-11eb-868b-bd60c856cffb.PNG)

**Comment by josemiguelvdz** [comment]
Hemos realizado retoques en la forma que los enemigos reciben daño y ya está arreglado.
