### ISSUE TITLE
Boss atascado

### ISSUE THREAD

**Issue by Yavi123** [josemiguelvdz/Bubble-Cat#9]
% Javier Villegas
% 25/05/2021

### Descripción

Si fallamos a la hora de quitar una tuerca Bastet deja de atacar y pasa a ser inmortal en vez de reiniciar la fase anterior

### Pasos 

1. Una vez aparezca una tuerca (independientemente de la fase), no quitarla dentro del límite de 15 segundos.

**Comment by josemiguelvdz** [comment]
Era un problema con la máquina de estados del jefe, ya ha sido arreglado.
